# Generated by Django 4.2.4 on 2023-08-30 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, blank=True)),
                ('arm_day', models.TextField(max_length=1000, blank=True)),
                ('shoulder_day', models.TextField(max_length=1000, blank=True)),
                ('back_day', models.TextField(max_length=1000, blank=True)),
                ('chest_day', models.TextField(max_length=1000, blank=True)),
                ('leg_day', models.TextField(max_length=1000, blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
